## Numpy Array Operations


In [1]:
import numpy as np

## Slicing

In [4]:
arr = np.arange(11)

print("Basic slicing", arr[2:7])
print("Slicing with step", arr[2:10:2])
print("Negative indexing", arr[-1], arr[-2], arr[-3])

Basic slicing [2 3 4 5 6]
Slicing with step [2 4 6 8]
Negative indexing 10 9 8


## Selection

In [13]:
arr_2D = np.array([[1,2,3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2D[1,2])
print("Entire row:", arr_2D[1])
print("Entire column:", arr_2D[:, 1])

Specific element 6
Entire row: [4 5 6]
Entire column: [2 5 8]


## Sorting


In [18]:
unsorted = np.array([3,2,6,4,1,8,9,7])
sorted = np.sort(unsorted)
print("sorted arr", sorted)


unsorted2D = np.array([[3, 2], 
                       [1,3], 
                       [2,1]])
sorted2Dcol = np.sort(unsorted2D, axis=0)
sorted2Drow = np.sort(unsorted2D, axis=1)

print("Sorted 2D array by column:\n", sorted2Dcol)
print("Sorted 2D array by row:\n", sorted2Drow)

sorted arr [1 2 3 4 6 7 8 9]
Sorted 2D array by column:
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row:
 [[2 3]
 [1 3]
 [1 2]]


## Filter

In [19]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

even_nums = numbers[numbers % 2 == 0];

print("print even number:", even_nums)

print even number: [2 4 6 8]


## Filter with Mask

In [21]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [6 7 8 9]


## Fancy indexing vs np.where()

In [25]:
indices = [2, 4, 5]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) 
print(numbers[where_result])

[3 5 6]
(array([5, 6, 7, 8]),)
[6 7 8 9]


In [27]:
conditionArray = np.where(numbers > 5, numbers + 3, numbers)
print(conditionArray)

[ 1  2  3  4  5  9 10 11 12]


## Merging

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

merged = np.concatenate((arr1, arr2))
print("merged Array\n", merged)

merged Array
 [1 2 3 4 5 6]


## Array compatibility 

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility Shaped", a.shape == b.shape)

Compatibility Shaped True


## Adding new Row and Col

In [33]:
original = np.array([[1, 2], [3, 4]])
print("original:\n", original)

newRow = np.array([5, 6])
with_new_row = np.vstack((original, newRow))
print("\nWith new Row:\n", with_new_row)

newCol = np.array([[7, 8], [9, 10]])
with_new_col = np.hstack((original, newCol))
print("\nWith new Col:\n", with_new_col)


original:
 [[1 2]
 [3 4]]

With new Row:
 [[1 2]
 [3 4]
 [5 6]]

With new Col:
 [[ 1  2  7  8]
 [ 3  4  9 10]]


## Deleting

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# deleted = np.delete(arr,2)

deleted = np.delete(arr,[1,2])
print("deleted array:", deleted)

deleted array: [1 4 5 6 7 8]
