## Numpy array and Basics
learn about numpy with chai or code


In [6]:
import numpy as np

## Creating Array and its bacis

In [7]:
arr_1d = np.array([1, 2, 3])
print("1D array:", arr_1d);

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3]
2D array: [[1 2 3]
 [4 5 6]]


In [13]:
py_list = [1, 2, 3]
print("Pyhton list multiplication:", py_list* 2)

np_array = np.array([1, 2, 3])
print("Numpy array multiplication:" ,np_array* 2)


import time

start = time.time()

list = [i * 2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)


start = time.time()

array = np.arange(1000000)*2
print("\n Numpy operation time:", time.time() - start)

Pyhton list multiplication: [1, 2, 3, 1, 2, 3]
Numpy array multiplication: [2 4 6]

 List operation time: 0.03436994552612305

 Numpy operation time: 0.0013208389282226562


## Creating array from scrath


In [20]:
zeros = np.zeros((3, 4))
print("Array of Zeros: \n", zeros)

ones = np.ones((2, 3))
print("Array of ones: \n", ones)

full = np.full((3, 3), 11)
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence);

Array of Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[11 11 11]
 [11 11 11]
 [11 11 11]]
Random array: 
 [[0.5964     0.31649322 0.20299541]
 [0.42478551 0.8849087  0.6917656 ]]
Sequence array: 
 [0 2 4 6 8]


## Vector Matrix & Tensor

In [22]:
vector = np.array([1, 2, 3])
print("Vector\n", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("matrix\n", matrix)


tensor = np.array([[[1,2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor\n", tensor)

Vector
 [1 2 3]
matrix
 [[1 2 3]
 [4 5 6]]
Tensor
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Prperties

In [23]:
arr= np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("dtype:", arr.dtype)
print("Size:", arr.size)

Shape: (2, 3)
Dimension: 2
dtype: int64
Size: 6


### Array ReShaping

In [25]:
arr = np.arange(12)
print("Array:", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped:\n", reshaped)

flattened = reshaped.flatten();
print("Flattened:\n", flattened)

# returns view instead of copy
raveled = reshaped.ravel()
print("Raveled:\n", raveled)


transpose = reshaped.T
print("Transpose:\n", transpose)


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
